"use client";
import { useRef } from "react";
import { useEffect, useState } from "react";
import type { Data, Layout } from "plotly.js";


type Params = { input_drive_mv:number; tau_m_ms:number; v_rest_mv:number; v_threshold_mv:number; v_reset_mv:number; refractory_ms:number; duration_ms:number; seed:number };
type Stats = { spike_count:number; firing_rate_hz:number; mean_isi_ms:number|null; cv_isi:number|null };
type Result = { kind:"simulation"; model_name:string; software_version:string; dt_ms:number; parameters:Params; time_ms:number[]; voltage_mv:number[]; spike_times_ms:number[]; statistics:Stats };
type Demo = { kind:"synthetic_demo"; seed:number; duration_ms:number; rate_hz:number; spike_trains_ms:number[][]; statistics:Stats };
type Dataset = { dandiset_id:string; title:string; authors:string[]; species:string[]; experimental_approach:string[]; source_url:string; doi:string|null; license:string[]; recording_information:string|null };
const initial:Params = { input_drive_mv:22, tau_m_ms:20, v_rest_mv:-65, v_threshold_mv:-50, v_reset_mv:-65, refractory_ms:2, duration_ms:500, seed:42 };
const fields: { key:keyof Params; label:string; unit:string; step:number }[] = [
  { key:"input_drive_mv",label:"Input drive (R × I)",unit:"mV",step:1 }, { key:"tau_m_ms",label:"Membrane time constant",unit:"ms",step:1 },
  { key:"v_rest_mv",label:"Resting potential",unit:"mV",step:1 }, { key:"v_threshold_mv",label:"Threshold",unit:"mV",step:1 },
  { key:"v_reset_mv",label:"Reset potential",unit:"mV",step:1 }, { key:"refractory_ms",label:"Refractory period",unit:"ms",step:.5 },
  { key:"duration_ms",label:"Duration",unit:"ms",step:50 }, { key:"seed",label:"Random seed",unit:"",step:1 }
];
function Chart({ data, yTitle }:{data:Data[];yTitle:string}) {
  const chart = useRef<HTMLDivElement>(null);
  useEffect(() => { const layout:Partial<Layout> = { paper_bgcolor:"#111b27",plot_bgcolor:"#111b27",font:{color:"#9aaebd",size:12},margin:{l:55,r:12,t:12,b:45},xaxis:{title:{text:"Time (ms)"},gridcolor:"#263848"},yaxis:{title:{text:yTitle},gridcolor:"#263848"},showlegend:false };
  const node = chart.current; let active = true; import("plotly.js-basic-dist-min").then(mod => { if (active && node) void mod.newPlot(node, data, layout, {displayModeBar:false,responsive:true}); }); return () => { active = false; import("plotly.js-basic-dist-min").then(mod => { if (node) mod.purge(node); }); }; }, [data, yTitle]); return <div ref={chart} style={{width:"100%",height:"280px"}} />;
}
function Header() {
  const links = [["Home","#home"],["Real Data","#real-data"],["Neuron Lab","#neuron-lab"],["Network Lab","#network-lab"],["Plasticity Lab","#plasticity-lab"],["Compare","#compare"],["About","#about"]];
  return <header className="sticky top-0 z-20 border-b border-line bg-ink/95 backdrop-blur"><nav aria-label="Main navigation" className="mx-auto flex max-w-7xl flex-wrap items-center gap-x-6 gap-y-3 px-6 py-4"><a href="#home" className="mr-auto text-lg font-bold text-mint">◌ NeuroSim Lab</a>{links.map(([label,href])=><a key={href} href={href} className="text-sm text-muted hover:text-white">{label}</a>)}</nav></header>;
}
function Hero() {
  const nodes = Array.from({length:17},(_,i)=>({x:8+(i*37)%84,y:12+(i*29)%74}));
  return <section id="home" className="grid-bg border-b border-line"><div className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-20 lg:grid-cols-2 lg:py-28"><div><p className="label">Computational neuroscience / open science</p><h1 className="mt-5 text-5xl font-bold tracking-tight md:text-7xl">NeuroSim <span className="text-mint">Lab</span></h1><p className="mt-5 max-w-xl text-xl leading-relaxed text-muted">Explore how neural activity emerges from neurons, networks, and synaptic plasticity.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#neuron-lab" className="rounded-lg bg-mint px-5 py-3 font-semibold text-ink hover:bg-white">Run a neuron model →</a><a href="#real-data" className="rounded-lg border border-line px-5 py-3 font-semibold hover:border-mint">Explore data sources</a></div><p className="mt-7 text-sm text-muted">Phase 1 · LIF simulation · synthetic spike demo · live DANDI metadata</p></div><div className="card relative h-80 overflow-hidden bg-[#0e1924]" aria-label="Animated abstract neural network schematic" role="img"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-full w-full">{nodes.slice(0,-1).map((n,i)=><line key={i} x1={n.x} y1={n.y} x2={nodes[(i*5+3)%nodes.length].x} y2={nodes[(i*5+3)%nodes.length].y} stroke="#4b8b85" strokeOpacity=".35" strokeWidth=".25" />)}{nodes.map((n,i)=><circle key={i} cx={n.x} cy={n.y} r={i%4===0?1.3:.8} fill="#91e6cb" opacity=".75"><animate attributeName="opacity" values=".3;1;.3" dur={String(2+i%4)+"s"} repeatCount="indefinite" /></circle>)}</svg><div className="absolute bottom-4 left-5 rounded bg-ink/80 px-3 py-2 font-mono text-xs text-mint">SIMULATED NETWORK SCHEMATIC</div></div></div></section>;
}
function Pipeline() {
  const stages=["Real neural data","Spike analysis","Neuron model","Spiking network","Synaptic plasticity","Biological / model comparison"];
  return <section className="border-b border-line bg-[#0e1721] px-6 py-10"><div className="mx-auto max-w-7xl"><p className="label mb-5">Research workflow</p><div className="flex flex-wrap items-center gap-3">{stages.map((stage,i)=><div key={stage} className="flex items-center gap-3"><span className="rounded border border-line px-3 py-2 text-xs font-semibold uppercase tracking-wide">{stage}</span>{i<stages.length-1&&<span className="text-mint">→</span>}</div>)}</div></div></section>;
}
function NeuronLab() {
  const [params,setParams]=useState<Params>(initial),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  async function run(p:Params) { setLoading(true);setError("");try { const r=await fetch("/api/lif",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});if(!r.ok)throw new Error(r.status===422?"Check parameter ranges and keep rest/reset below threshold.":"Simulation API unavailable. Start the backend.");setResult(await r.json());}catch(e){setError(e instanceof Error?e.message:"Could not run simulation.");}finally{setLoading(false);} }
  useEffect(()=>{fetch("/api/lif",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(initial)}).then(r=>r.ok?r.json():Promise.reject()).then(setResult).catch(()=>setError("Simulation API unavailable. Start the backend."));},[]);
  return <section id="neuron-lab" className="mx-auto max-w-7xl scroll-mt-24 px-6 py-20"><p className="label">01 / Model</p><h2 className="section-title mt-3">Single Neuron Lab</h2><p className="mt-3 max-w-3xl text-muted">A leaky integrate-and-fire neuron accumulates a constant input drive, leaks toward rest, and emits a mathematical spike at threshold. The reset is a model rule, not the shape of a biological action potential.</p><div className="mt-8 grid gap-6 lg:grid-cols-[320px_1fr]"><div className="card p-5"><h3 className="font-semibold">Parameters</h3><div className="mt-5 space-y-4">{fields.map(({key,label,unit,step})=><label key={key} className="block text-sm text-muted"><span className="mb-1 flex justify-between"><span>{label}</span><span>{unit}</span></span><input aria-label={label} type="number" step={step} value={params[key]} onChange={e=>setParams({...params,[key]:Number(e.target.value)})} className="w-full rounded-md border border-line bg-ink px-3 py-2 text-white" /></label>)}</div><button onClick={()=>void run(params)} disabled={loading} className="mt-6 w-full rounded-md bg-mint px-4 py-3 font-bold text-ink disabled:opacity-60">{loading?"Simulating…":"Run simulation"}</button><p className="mt-4 text-xs leading-relaxed text-muted">Fixed step: 0.1 ms. Seed is recorded; this deterministic model does not use randomness.</p></div><div className="space-y-5"><div className="card p-5"><div className="flex justify-between"><h3 className="font-semibold">Membrane potential</h3><span className="label">Simulated</span></div>{result?<Chart yTitle="Voltage (mV)" data={[{x:result.time_ms,y:result.voltage_mv,type:"scatter",mode:"lines",line:{color:"#91e6cb",width:2}}]} />:<p className="py-20 text-center text-muted">{loading?"Running model…":"Start the backend to view the voltage trace."}</p>}</div><div className="card p-5"><h3 className="font-semibold">Spike events</h3>{result?<Chart yTitle="Neuron" data={[{x:result.spike_times_ms,y:result.spike_times_ms.map(()=>1),type:"scatter",mode:"markers",marker:{color:"#e7bb80",size:9,symbol:"line-ns-open"}}]} />:<p className="py-12 text-center text-muted">No result yet.</p>}</div>{result&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Spikes",result.statistics.spike_count],["Rate",String(result.statistics.firing_rate_hz)+" Hz"],["Mean ISI",result.statistics.mean_isi_ms===null?"—":String(result.statistics.mean_isi_ms)+" ms"],["ISI CV",result.statistics.cv_isi??"—"]].map(([k,v])=><div className="card p-4" key={k}><p className="text-xs text-muted">{k}</p><p className="mt-2 text-xl font-bold text-mint">{v}</p></div>)}</div>}{error&&<p role="alert" className="rounded border border-rose-700 p-3 text-rose-300">{error}</p>}</div></div></section>;
}
function RealData() {
  const [query,setQuery]=useState("electrophysiology"),[datasets,setDatasets]=useState<Dataset[]>([]),[demo,setDemo]=useState<Demo|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  useEffect(()=>{fetch("/api/demo").then(r=>r.ok?r.json():Promise.reject()).then(setDemo).catch(()=>{});},[]);
  async function search(){setLoading(true);setError("");setDatasets([]);try{const r=await fetch("/api/dandi/search?q="+encodeURIComponent(query.trim()));if(!r.ok)throw new Error("DANDI metadata unavailable. The synthetic demo is separate from real datasets.");setDatasets(await r.json());}catch(e){setError(e instanceof Error?e.message:"Search failed.");}finally{setLoading(false);}}
  return <section id="real-data" className="scroll-mt-24 border-y border-line bg-[#0e1721]"><div className="mx-auto max-w-7xl px-6 py-20"><p className="label">02 / Public archive</p><h2 className="section-title mt-3">Real Neural Data Explorer</h2><p className="mt-3 max-w-3xl text-muted">Search public DANDI Dandiset metadata. Phase 1 does not fetch recordings or real spike times. Missing archive fields are shown as unavailable.</p><div className="mt-7 flex max-w-xl gap-2"><input aria-label="Search DANDI datasets" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void search();}} className="min-w-0 flex-1 rounded-md border border-line bg-ink px-4 py-3" /><button onClick={()=>void search()} disabled={loading||query.trim().length<2} className="rounded-md bg-mint px-5 font-bold text-ink disabled:opacity-50">{loading?"Searching…":"Search"}</button></div>{error&&<p role="alert" className="mt-4 text-rose-300">{error}</p>}{datasets.length>0&&<div className="mt-7 grid gap-4 md:grid-cols-2">{datasets.map(d=><article key={d.dandiset_id} className="card p-5"><p className="label">Dandiset {d.dandiset_id} · Real metadata</p><h3 className="mt-2 text-lg font-semibold">{d.title}</h3><dl className="mt-4 space-y-2 text-sm text-muted">{[["Authors",d.authors.join(", ")],["Species",d.species.join(", ")],["Approach",d.experimental_approach.join(", ")],["Recording",d.recording_information],["DOI",d.doi],["License",d.license.join(", ")]].map(([label,value])=><div key={label}><dt className="inline text-slate-200">{label}: </dt><dd className="inline">{value||"Not available in search metadata"}</dd></div>)}</dl><a href={d.source_url} target="_blank" rel="noreferrer" className="mt-5 inline-block text-sm font-semibold text-mint underline">Original DANDI source ↗</a></article>)}</div>}{!loading&&!error&&datasets.length===0&&<p className="mt-4 text-sm text-muted">Enter a term and search the public archive.</p>}<div className="card mt-12 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="label">Synthetic demo · not a recording</p><h3 className="mt-2 font-semibold">Spike raster preview</h3></div>{demo&&<p className="text-sm text-muted">{demo.spike_trains_ms.length} neurons · seed {demo.seed} · target {demo.rate_hz} Hz</p>}</div>{demo?<Chart yTitle="Neuron index" data={demo.spike_trains_ms.map((train,i)=>({x:train,y:train.map(()=>i+1),type:"scatter",mode:"markers",marker:{color:"#91e6cb",size:5,symbol:"line-ns-open"}}))} />:<p className="py-16 text-center text-muted">Start the backend to view the labeled synthetic raster.</p>}<p className="text-xs text-muted">These are independent simulated Poisson spike trains. They do not represent any DANDI dataset.</p></div></div></section>;
}
function Planned() {
  const items=[["network-lab","Spiking Network Lab","Excitatory and inhibitory populations with seeded Brian2 simulations","Phase 2"],["plasticity-lab","Synaptic Plasticity Lab","Pair-based STDP learning windows and weight trajectories","Phase 2"],["compare","Biological / Model Comparison","Selected real recording statistics beside simplified simulations","Phase 3"]];
  return <section className="mx-auto grid max-w-7xl gap-4 px-6 py-16 md:grid-cols-3">{items.map(([id,title,description,phase])=><article id={id} key={id} className="card scroll-mt-24 p-6"><p className="label">{phase} / Planned</p><h2 className="mt-3 text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-relaxed text-muted">{description}</p></article>)}</section>;
}
function About() {
  return <section id="about" className="scroll-mt-24 border-t border-line bg-[#0e1721]"><div className="mx-auto max-w-7xl px-6 py-20"><p className="label">Methodology</p><h2 className="section-title mt-3">About the project</h2><div className="mt-7 grid gap-8 text-sm leading-relaxed text-muted md:grid-cols-2"><div><h3 className="text-lg font-semibold text-white">Why NeuroSim Lab?</h3><p className="mt-3">This computational neuroscience self-study connects mathematical neuron models, spike-train analysis, and public data provenance. The Next.js interface calls a FastAPI scientific backend. A provider layer queries DANDI metadata without downloading assets.</p><p className="mt-4">The LIF equation is integrated at a fixed 0.1 ms step. Constant input, threshold reset, and absolute refractoriness are explicit assumptions. The demo raster uses seeded independent Poisson processes.</p></div><div><h3 className="text-lg font-semibold text-white">Scientific limitations</h3><p className="mt-3">LIF neurons are simplified neuron models. SNN simulations are not direct reproductions of biological brains. STDP is one model of synaptic plasticity. Similarity between simulated and biological spike statistics does not establish biological equivalence.</p><p className="mt-4">DANDI search shows real archive metadata only. Recording signals and spike times require careful NWB asset selection and preprocessing in a later phase.</p></div></div><div className="mt-8 flex gap-5 text-sm text-mint"><a href="https://docs.dandiarchive.org/api/rest-api/" target="_blank" rel="noreferrer" className="underline">DANDI API documentation ↗</a><a href="https://www.nwb.org/" target="_blank" rel="noreferrer" className="underline">NWB ↗</a></div></div></section>;
}
export default function Page(){return <><Header/><main><Hero/><Pipeline/><NeuronLab/><RealData/><Planned/><About/></main><footer className="border-t border-line px-6 py-6 text-center text-xs text-muted">NeuroSim Lab · Open scientific software · Phase 1</footer></>;}

